### ISSUE TITLE
Posting of course link in Join course field in student account produces 404

### ISSUE THREAD

**Issue by chrfrantz** [JohanAanesen/NTNU-Bachelor-Management-System-For-CS-Assignments#51]
See title. Tried it with Chrome and Firefox. Using link for non-logged-in students works.

**Comment by BredeFK** [comment]
The link is for posting in the url. In the join course field it's only the hash

**Comment by BredeFK** [comment]
This now works as long as the hash is in the field an not 'blocked' by other chars in the front.
ex: `hashcode` would work but not `bhashcode`
