### ISSUE TITLE
Allow the setting of default weight and input type for a given form

### ISSUE THREAD

**Issue by chrfrantz** [JohanAanesen/NTNU-Bachelor-Management-System-For-CS-Assignments#56]
When starting to edit a form, the user should be able to specify the default type of entry (since it often repeats) and default weight (ideally on the left side under "Add new field") for any newly created field.

**Comment by kongebra** [comment]
4023040 implements this.

The fields `default_weight` & `default_type` is not stored persistant, so it needs to be set every time you edit the form. Don't see this as any problem at this stage.
