### ISSUE TITLE
Delivered count is wrong, counts teachers aswell

### ISSUE THREAD

**Issue by JohanAanesen** [JohanAanesen/NTNU-Bachelor-Management-System-For-CS-Assignments#65]
![image](https://user-images.githubusercontent.com/23040808/55001605-41147980-4fd5-11e9-8515-9ba2c34e4b45.png)

Correct count should be 37 I guess

**Comment by kongebra** [comment]
Specifing, the second number should be 37.

`32 / 37` is correct

**Comment by kongebra** [comment]
Fixed
