### ISSUE TITLE
Provide option to make selected items in forms optional in the form editor.

### ISSUE THREAD

**Issue by chrfrantz** [JohanAanesen/NTNU-Bachelor-Management-System-For-CS-Assignments#74]
Not all items don't necessarily need to be filled. Having an option to make an item optional selectively would be good.

**Comment by kongebra** [comment]
### NOTE 
This has changes in the database, so the application would need a new build for the database, or insert the new column in `fields` that is added.

#### SQL-changes
```sql
ALTER TABLE `fields`
ADD `required` INT(1) NOT NULL;
```
