### ISSUE TITLE
Indicate explicitly which assignments are open to submissions and which ones are closed.

### ISSUE THREAD

**Issue by chrfrantz** [JohanAanesen/NTNU-Bachelor-Management-System-For-CS-Assignments#76]
Just to make the overview of assignments more explicit, indicate the ones that are closed. and open (e.g. open, closed label). Perhaps an additional review label would be good for assignments that have a review stage.

**Comment by BredeFK** [comment]
We already are greying out the closed ones but we could have an label that says closed in addition too? 
![image](https://user-images.githubusercontent.com/32249338/55160430-9da59f00-5163-11e9-88c4-cd387f71008c.png)

**Comment by BredeFK** [comment]
When the deadline for the assignments passes, the number of peer reviewing left is displayed on all assignment cards including the deadline for the review (only deadline info for the admin)
